In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("Housing.csv")

In [ ]:
df.head(3)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

In [ ]:
df.tail(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
535,2100000,3360,2,1,1,yes,no,no,no,no,1,no,unfurnished
536,1960000,3420,5,1,2,no,no,no,no,no,0,no,unfurnished
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
539,1855000,2990,2,1,1,no,no,no,no,no,1,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df['price']

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [ ]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
df.shape

(545, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
df[['price','area']]

        price  area
0    13300000  7420
1    12250000  8960
2    12250000  9960
3    12215000  7500
4    11410000  7420
..        ...   ...
540   1820000  3000
541   1767150  2400
542   1750000  3620
543   1750000  2910
544   1750000  3850

[545 rows x 2 columns]

In [ ]:
df[df['price']>9800000],df[df['area']>7000]

(      price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
 0  13300000   7420         4          2        3      yes        no       no
 1  12250000   8960         4          4        4      yes        no       no
 2  12250000   9960         3          2        2      yes        no      yes
 3  12215000   7500         4          2        2      yes        no      yes
 4  11410000   7420         4          1        2      yes       yes      yes
 5  10850000   7500         3          3        1      yes        no      yes
 6  10150000   8580         4          3        4      yes        no       no
 7  10150000  16200         5          3        2      yes        no       no
 8   9870000   8100         4          1        2      yes       yes      yes

   hotwaterheating airconditioning  parking prefarea furnishingstatus
 0              no             yes        2      yes        furnished
 1              no             yes        3       no        furnished
 2              no              no        2      yes   semi-furnished
 3              no             yes        3      yes        furnished
 4              no             yes        2       no        furnished
 5              no             yes        2      yes   semi-furnished
 6              no             yes        2      yes   semi-furnished
 7              no              no        0       no      unfurnished
 8              no             yes        2      yes        furnished  ,
         price   area  bedrooms  bathrooms  stories mainroad guestroom  \
 0    13300000   7420         4          2        3      yes        no
 1    12250000   8960         4          4        4      yes        no
 2    12250000   9960         3          2        2      yes        no
 3    12215000   7500         4          2        2      yes        no
 4    11410000   7420         4          1        2      yes       yes
 ..        ...    ...       ...        ...      ...      ...       ...
 403   3500000  12944         3          1        1      yes        no
 452   3150000   9000         3          1        2      yes        no
 460   3087000   8100         2          1        1      yes        no
 473   3003000   8050         2          1        1      yes        no
 520   2450000   7700         2          1        1      yes        no

     basement hotwaterheating airconditioning  parking prefarea  \
 0         no              no             yes        2      yes
 1         no              no             yes        3       no
 2        yes              no              no        2      yes
 3        yes              no             yes        3      yes
 4        yes              no             yes        2       no
 ..       ...             ...             ...      ...      ...
 403       no              no              no        0       no
 452       no              no              no        2       no
 460       no              no              no        1       no
 473       no              no              no        0       no
 520       no              no              no        0       no

     furnishingstatus
 0          furnished
 1          furnished
 2     semi-furnished
 3          furnished
 4          furnished
 ..               ...
 403      unfurnished
 452   semi-furnished
 460      unfurnished
 473      unfurnished
 520      unfurnished

 [86 rows x 13 columns])

In [ ]:
df['price'].sum()

np.int64(2597867440)

In [ ]:
df[df['bedrooms']==2]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
61,7070000,8880,2,1,1,yes,no,no,no,yes,1,no,semi-furnished
66,6930000,13200,2,1,1,yes,no,yes,yes,no,1,no,furnished
73,6685000,6600,2,2,4,yes,no,yes,no,no,0,yes,furnished
91,6419000,6750,2,1,1,yes,yes,yes,no,no,2,yes,furnished
114,6020000,6800,2,1,1,yes,yes,yes,no,no,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2100000,3360,2,1,1,yes,no,no,no,no,1,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
539,1855000,2990,2,1,1,no,no,no,no,no,1,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df[df['basement']=='yes']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,2590000,3600,2,2,2,yes,no,yes,no,no,1,no,furnished
515,2450000,3210,3,1,2,yes,no,yes,no,no,0,no,unfurnished
527,2275000,1836,2,1,1,no,no,yes,no,no,0,no,semi-furnished
529,2275000,3970,3,1,2,yes,no,yes,no,no,0,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished

In [ ]:
df[df['basement'and'mainroad']=='yes']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
df['price'].mean()

np.float64(4766729.247706422)

In [ ]:
df['parking'].count()

np.int64(545)

In [ ]:
df['stories'].min()

1

In [ ]:
df['basement'].unique()

array(['no', 'yes'], dtype=object)